### PR TITLE
New biofuel_can texture

### PR DESCRIPTION
**Pull request by El-Naso**
I'd say this texture is about 90% done.

Color might need tweaking.
Shadows and highlights might need tweaking.
Need to add a subtle bevel to the sides.

### CODE REVIEW

**Comment by OgelGames** [comment]
Personally I prefer the original texture, but it doesn't really matter for me because I can easily override it with my client texture pack.

**Comment by BuckarooBanzay** [comment]
I kinda like the new texture:
screenshot_20201204_132422

> Personally I prefer the original texture, but it doesn't really matter for me because I can easily override it with my client texture pack.

How do we deal with disagreements here anyway?
Personally i like some changes from the original mods, its refreshing and it does not look like in every other server...

**Comment by OgelGames** [comment]
> How do we deal with disagreements here anyway?

I don't think we can really, textures are subjective, and there will always be some that like them, and some that don't...

I think if textures are at least liked by someone, then we should just add them, if players start to complain about a new texture (like what happened with wifi chest), then we can easily remove it again.

**Comment by BuckarooBanzay** [comment]
> I'd say this texture is about 90% done.

Is this ready to merge? It looks pretty good IMO...

**Comment by El-Naso** [comment]
Yeah, it's basically done and even if I redo it it will be almost identical with some fixes.

**Pull request merged**
