### PR TITLE
Christmas textures

### PR DESCRIPTION
**Pull request by OgelGames**
Basic idea: christmas-ify various textures, based on Minecraft's [easter egg](https://minecraft.gamepedia.com/Easter_eggs#Christmas).

**TODO:**
* [X] Santa hats for NPCs
* [x] Christmas present bones
* [x] Decorations on tree leaves and saplings (like [this](https://static.planetminecraft.com/files/resource_media/screenshot/12548131-lights.png))
* [x] Tree cones as larger decorations
* [X] Candy cane bread
* [x] Color-changing light (`default:torch`)

More ideas could be taken from this Minecraft texture pack: https://www.planetminecraft.com/texture-pack/christmas-pack-4446425

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
nice idea :+1: 

>  Decorations on tree leaves (like this)

Do you have some (free?) textures ready for that? i might have some time to do this...

>  Candy cane default:torch (possibly also override in pandorabox-custom to make them edible?)

This could be done in https://github.com/mt-mods/christmas (depending on the `christmas_toggle` flag :thinking:

**Comment by OgelGames** [comment]
> > Decorations on tree leaves (like this)
> 
> Do you have some (free?) textures ready for that? i might have some time to do this...

No, haven't started on any of the other textures yet, go right ahead 👍 

I'm not sure how many trees the decorations should be put on, but I think at least the pine, spruce, fir, and maybe ceder trees, because those are used IRL for christmas trees. Also the spruce, fir, and ceder cones could be made into decorations too.

**Comment by BuckarooBanzay** [comment]
i made a custom mod for the christmas overlays, so the additional textures can be removed again:
https://github.com/pandorabox-io/christmas_tree_overlays

So far i've only made an override for the `pine` leaves with some textures i found here: https://github.com/crazyginger72/xmas

screenshot_20201218_112351

**Comment by OgelGames** [comment]
> so the additional textures can be removed again

Can't that be done just be removing the textures from the texture pack? 😕

**Comment by S-S-X** [comment]
> > so the additional textures can be removed again
> 
> Can't that be done just be removing the textures from the texture pack?

Any way to keep textures and allow somehow selecting different (seasonal) variants to use? I think that would be best solution, removing textures does not sound like real nice resolution.

**Comment by OgelGames** [comment]
> Any way to keep textures and allow somehow selecting different (seasonal) variants to use?

I was thinking move them into a subfolder like `.christmas` to disable them, same thing can be done for any other textures.

**Comment by OgelGames** [comment]
screenshot_20201218_224332

**Comment by BuckarooBanzay** [comment]
> Can't that be done just be removing the textures from the texture pack? confused

Sounds good too (you are fast! :astonished:)

> I was thinking move them into a subfolder like .christmas to disable them, same thing can be done for any other textures.

Its a once-every year thing at most, so i guess thats ok, it won't spam the commit-log i guess...

**Comment by OgelGames** [comment]
I moved the textures into the subfolder, now all that needs to be done to disable them is add "`.`" to the folder name :wink:

**Comment by S-S-X** [comment]
> I moved the textures into the subfolder, now all that needs to be done to disable them is add "`.`" to the folder name

As moving files is not that nice for git history would it be possible to keep it hidden and use symlink to make textures available? Yeah everything feels hacky but could possibly be bit cleaner compared to other bubblegum?

**Comment by OgelGames** [comment]
> would it be possible to keep it hidden and use symlink to make textures available?

It should work, it worked nicely for the cherrytree and bamboo mods: https://github.com/pandorabox-io/pandorabox-mods/commit/502f2f1ff75c47f3af4a8637b045e42cacdcc650

But it does also make it annoying to use for Windows users (me), because they don't work on Windows...

**Comment by BuckarooBanzay** [comment]
> As moving files is not that nice for git history would it be possible to keep it hidden and use symlink to make textures available? Yeah everything feels hacky but could possibly be bit cleaner compared to other bubblegum?

How about using branches for special occasions?
* `master` for the main stuff
* `christmas` / `easter` etc for the other stuff (`master` can be merged onto the branch at any time)

just an idea, i may be biased (everything is a nail if you have a hammer)

**Comment by OgelGames** [comment]
> How about using branches for special occasions?

If that works it would be a good solution, but I'm not sure how changing branches works with the auto-update thing...

**Comment by OgelGames** [comment]
screenshot_20201219_232906

**Comment by S-S-X** [comment]
> > As moving files is not that nice for git history would it be possible to keep it hidden and use symlink to make textures available? Yeah everything feels hacky but could possibly be bit cleaner compared to other bubblegum?
> 
> How about using branches for special occasions?
> 
> * `master` for the main stuff
> * `christmas` / `easter` etc for the other stuff (`master` can be merged onto the branch at any time)
> 
> just an idea, i may be biased (everything is a nail if you have a hammer)

That will probably look like a good idea at first and works for some time but when you start merging stuff between branches it most probably turns to nightmare. Tried to do that with few simple things and it usually turned out to be very bad idea that seems at first to be very good way to manage things.

**Comment by OgelGames** [comment]
All the textures are ready, unless there is anything else anyone wants to add, I think this is ready to merge.

**Comment by BuckarooBanzay** [comment]
merging this... :christmas_tree: :gift: 

> That will probably look like a good idea at first and works for some time but when you start merging stuff between branches it most probably turns to nightmare. Tried to do that with few simple things and it usually turned out to be very bad idea that seems at first to be very good way to manage things.

Maybe we can figure out where this is going along the way, multiple repositories could be an option too :thinking: 

**EDIT**: oh ,right: the custom textures are still sent over UDP because the media-collector ~~monstrosity~~thing (https://github.com/BuckarooBanzay/minetest_manager/blob/master/jobs/collectstatic.sh) does not go over that yet, i need to figure out a clean way too to do this...

**Comment by BuckarooBanzay** [comment]
> > > As moving files is not that nice for git history would it be possible to keep it hidden and use symlink to make textures available? Yeah everything feels hacky but could possibly be bit cleaner compared to other bubblegum?
> > 
> > 
> > How about using branches for special occasions?
> > 
> > * `master` for the main stuff
> > * `christmas` / `easter` etc for the other stuff (`master` can be merged onto the branch at any time)
> > 
> > just an idea, i may be biased (everything is a nail if you have a hammer)
> 
> That will probably look like a good idea at first and works for some time but when you start merging stuff between branches it most probably turns to nightmare. Tried to do that with few simple things and it usually turned out to be very bad idea that seems at first to be very good way to manage things.

Maybe we can move the christmas-related textures to a new repository (`pandorabox-christmas-textures`?) and pull both texture packs in when there is an event like that, afaik multiple texture-packs _should_ work, haven't tried that though..
(it is currently mapped as `server` modpack-folder but it can be moved up one folder https://github.com/pandorabox-io/pandorabox.io/blob/master/docker-compose.yml#L18 to `server/main` and `server/<whatever-event>`)

**Comment by OgelGames** [comment]
Sounds good 👍 And yes it will work, same as it has for the subfolder here 😉

**Comment by OgelGames** [comment]
FYI (if you didn't notice), I moved the christmas textures to here: https://github.com/mt-mods/christmas_textures

Interestingly, removing the textures caused some ~~errors~~ warnings on the following restart:
```
2021-01-03 09:53:41: ERROR[Server]: Server::sendRequestedMedia(): Could not open "/root/.minetest/textures/server/christmas/bones_bottom.png" for reading
2021-01-03 09:53:41: ERROR[Server]: Server::sendRequestedMedia(): Could not open "/root/.minetest/textures/server/christmas/bones_front.png" for reading
2021-01-03 09:53:41: ERROR[Server]: Server::sendRequestedMedia(): Could not open "/root/.minetest/textures/server/christmas/bones_rear.png" for reading
etc ...
```

**Comment by BuckarooBanzay** [comment]
i saw something like that too before, happens mostly while renaming/removing textures and not restarting the server

**Pull request merged**
